# new-otel-collector-config.yaml

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.103.0

mode: daemonset

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch: {}

  exporters:
    loki:
      endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
    logging:
      loglevel: debug

  # This 'service' block is for the collector itself
  service:
    
    # [FIX] This block moves the internal
    # metrics port from 8888 to 8889
    telemetry:
      metrics:
        address: 0.0.0.0:8889

    # This 'pipelines' block was already here
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [loki, logging]
